version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "xpack.security.transport.ssl.enabled=false"
      - "ELASTIC_PASSWORD=Tec1Admin4
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - "ELASTICSEARCH_USERNAME=elastic
      - "ELASTICSEARCH_PASSWORD=Tec1Admin4
    ports:
      - "5601:5601"
    networks:
      - elk

networks:
  elk:
    driver: bridge

